### PR TITLE
Update drushrc file to automatically detect and configure uri option

### PR DESCRIPTION
**Pull request by wxactly**

### CODE REVIEW

**Review by unclegcb — APPROVED** [review]
This looks great. Any concerns about overwriting existing drushrc.php? People might have their own customizations.

**Comment by mariacha** [comment]
That's a really good point -- I think as long as it's in the .drush folder we'll be ok, so you could do this in something like `ts.drushrc.php`

**Comment by wxactly** [comment]
@unclegcb @mariacha - I would love to get this into its own file if possible... Two thoughts there though. First, I think `drushrc.php` is the [canonical name for this file](http://api.drush.org/api/drush/examples%21example.drushrc.php/master)... Will it autoload other files? How does that work?

Second, as part of the new php install script, I had everyone copy this drushrc file into their `~/.drush` directory and I didn't see any `cp` commands stop with a confirmation for overwriting an existing file... so I believe everyone (or almost everyone) is running the current version of this file in `master`

**Comment by wxactly** [comment]
The line `cp -n config/drushrc.php ~/.drush` that I added to the install script won't copy the file if it already exists because of the `-n` flag

**Comment by mariacha** [comment]
It must be autoloaded. Check out my .drush folder:

screen shot 2018-05-09 at 9 22 45 am

**Comment by wxactly** [comment]
@mariacha - I just tried `ts.drushrc.php` and it's not loading for me unfortunately...

Looks like there is special accommodation for loading `aliases.drushrc.php` files... but I think those would only apply options to when using aliases - right? Not for drush in general? http://api.drush.org/api/drush/examples%21example.aliases.drushrc.php/master

**Comment by mariacha** [comment]
I led you astray -- it must only autoload x.aliases.drushrc.php files, because this isn't loading for me. Sorry --  I should have tested more carefully.

**Comment by wxactly** [comment]
It's okay! Just put it back again... wish there was an easier way to autoload the `drushrc`

**Comment by mariacha** [comment]
Cool -- This works great. 👍

**Comment by wxactly** [comment]
Thanks for testing @mariacha @unclegcb!

**Pull request merged**
