### PR TITLE
Terminus

### PR DESCRIPTION
**Pull request by robertjpotter**
**Conversion instructions**

If you want to switch from terminus via composer to terminus via homebrew, first update your existing version so all your configuration files get updates. Then remove via cgr and install via brew:

```
cgr update pantheon-systems/terminus
<run a terminus command and follow any update instructions>
cgr remove pantheon-systems/terminus
brew install pantheon-systems/external/terminus
```

### CODE REVIEW

**Comment by unclegcb** [comment]
I love consolidating on Brew as much as feasible. @wxactly was there another reason not to use Brew for terminus other than availability?

**Review by wxactly — APPROVED** [review]
A long time ago we installed most of our global php packages (drush, drupal console, etc) via the homebrew/php tap. But after that closed down, we standardized around `cgr` (wrapper around `composer global`) instead.

There's a part of me that likes keeping all of the php software in composer land... There are definitely some benefits, like being able to easily install different drush versions, for example. But we always want the latest terminus executable, and I like that this formula is actually maintained by pantheon-systems.

@robertjpotter @unclegcb - if somebody switches their terminus over from composer to homebrew, would you mind pasting manual steps of how to accomplish that here in the PR description?

**Comment by Greg-Boggs** [comment]
Thanks for doing the cooking on this project in public issues! I use this project on one of my laptops at the Multco Library and it's fantastic to have.

**Comment by unclegcb** [comment]
@wxactly instructions added!

**Pull request merged**
