### PR TITLE
Add capacity for a separate virtual host at .dv8, pointing to /web in…

### PR DESCRIPTION
**Pull request by unclegcb**
… the Sites directory.

This is for drupal 8 compatibility!

### CODE REVIEW

**Comment by wxactly** [comment]
Actually, @unclegcb - this works for me, without any configuration change:

```
<VirtualHost *:8080>
  ServerName dev
  ServerAlias *.dev

  CustomLog "/Users/wxactly/Sites/logs/dev-access_log" combinedmassvhost
  ErrorLog "/Users/wxactly/Sites/logs/dev-error_log"

  VirtualDocumentRoot /Users/wxactly/Sites/%-2+

  RewriteEngine on
  RewriteCond %{HTTP_HOST} ^(.*)\.dev$ [NC]
  RewriteCond /Users/wxactly/Sites/%1/web -d
  RewriteRule (.*) http://localhost/%1/web$1 [P,L]
</VirtualHost>
```

Automatically detects a "web" directory and serves up `*.dev` from there if it exists. I haven't gotten it working for https yet, but this seems much easier than trying to remember which tld to use for your site

**Comment by wxactly** [comment]
There's also this version which is less magical, and a little more flexible:

```
<VirtualHost *:8080>
  ServerName dev
  ServerAlias *.dev

  CustomLog "/Users/wxactly/Sites/logs/dev-access_log" combinedmassvhost
  ErrorLog "/Users/wxactly/Sites/logs/dev-error_log"

  VirtualDocumentRoot /Users/wxactly/Sites/%-2+

  RewriteEngine on
  RewriteCond %{HTTP_HOST} ^(.*)\.(.*)\.dev$ [NC]
  RewriteRule (.*) http://localhost/%2/%1$1 [P,L]
</VirtualHost>
```

Which automatically serves up `http://test.dev` from `~/Sites/test` like usual, but additionally serves up `http://*.test.dev` from `~/Sites/test/*`. So for drupal-composer projects, the address would be `http://web.test.dev`

**Comment by levelos** [comment]
You guys are smart, good stuff.

**Comment by unclegcb** [comment]
The only problem I have with the really magical one is that you can break your site by adding a directory called "web" in the root. Perhaps we should be checking for index.php? If we can do that, I think the magical one is great!

**Comment by wxactly** [comment]
The setup script is no longer installing httpd, so closing this PR. With the new nginx setup in master, `http://*.foo.dev/` serves up your app from `~/Sites/foo/*`

**Pull request closed without merging**
