### PR TITLE
Pull ssl into a separate script and add entries for all ~/Sites

### PR DESCRIPTION
**Pull request by wxactly**
So that the certificate is "legit enough" to be manually trusted.

### CODE REVIEW

**Comment by wxactly** [comment]
Instructions on how to manually trust the cert in OSX can be found various places on the internet e.g. [Adding the Certificate to macOS Keychain](https://deliciousbrains.com/https-locally-without-browser-privacy-errors/#macos-keychain)

**Comment by mariacha** [comment]
screen shot 2017-12-26 at 10 22 31 am

Trying to double-click the ssl, I see this error and don't know what to do after that. 

This is after running `./scripts/ssl.sh` and that's it -- are there other steps?

**Comment by wxactly** [comment]
@mariacha Make sure you're adding it to your login keychain? Is the certificate in the list if you scroll down to "T"?

As long as you're on the new *.localhost stack, you should just need to run `./scripts/ssl.sh`

**Review by unclegcb — APPROVED** [review]

**Comment by mariacha** [comment]
It all works for me now -- It was not trying to add the cert to my login set, as you suggested.

**Pull request merged**
