### PR TITLE
Replace httpd with nginx

### PR DESCRIPTION
**Pull request by wxactly**
For #11. Setup steps:

Make sure you're inside a `ts_environment` working copy so you can run the nginx setup script (`git clone git@github.com:thinkshout/ts_environment.git && cd ts_environment`)

```
brew services stop httpd22
brew services stop httpd24
brew services stop httpd

brew cleanup
brew uninstall mod_fastcgi
brew uninstall httpd22 --force
brew uninstall httpd24 --force
brew uninstall httpd --force

brew install nginx
./scripts/nginx.sh
```

And then add `cgi.fix_pathinfo = 0` to `php.ini` for each version of php that you have installed. These config files are generally in `/usr/local/etc/php/X.X/conf.d/php-ts.ini` but may be a slightly different file depending on when you set up your environment.

While you're editing `php-ts.ini`, can also opt to set your php error log to a consistent location: `error_log = /usr/local/var/log/php-error.log`

When the upgrade is complete, you can also trash these files which are no longer used:
```
~/Sites/httpd-vhosts.conf
~/Sites/ssl/
~/Sites/logs/
```

### CODE REVIEW

**Comment by tauno** [comment]
@wxactly Am I reading this right that for a sub directory web root you would use `web.tror.dev` rather than `tror.dev`?

What are the steps to upgrade?

**Comment by wxactly** [comment]
Yeah that's right @tauno - so all of our sites with subdirectory web roots will work out of the box with no extra configuration! Other options would be to clone the project into `~/Projects` and then symlink the web root to `~/Sites`, or [set up a virtual host](https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/) in `/usr/local/etc/nginx/servers`. (I was thinking about getting a simple vhost example together that would be easy for folks to copy/paste if they needed it... wanted to make sure all this was working first...)

**Comment by wxactly** [comment]
@tauno - Added setup steps to the description. Totally untested! Hopefully they work 😅

**Comment by tauno** [comment]
Made some updates to the overview instructions, but looks good.

I also did a `brew cleanup` first since it warns about other old versions of httpd that were previously installed.

**Review by tauno — APPROVED** [review]

**Pull request merged**
