### PR TITLE
Switch composer command

### PR DESCRIPTION
**Pull request by wxactly**

### CODE REVIEW

**Review by bdimaggio — COMMENTED** [review]
I love it!

A note that may affect no one but me: I had `composer` aliased to `php -d memory_limit=-1 /usr/local/bin/composer $1`, I think in order to address memory-limit issues in a specific situation. `sc` didn't work until I removed that alias. I suppose we could address that for anyone else who took that approach by changing our composer call here to `/usr/local/bin/composer`, but I'm not sure whether that alias/hack is common enough to merit the change. What do you think?

**Comment by wxactly** [comment]
Thanks for the review @bdimaggio! We've actually already fixed composer memory limit issues _in this repo_ so I would probably rather humbly suggest removing any composer alias on your local machine and put in the more holistic fix instead: https://github.com/thinkshout/ts_environment/pull/36/files

That said, I also went ahead and changed the command here to use `\composer` so that it invokes composer directly without aliases

**Review by bdimaggio — APPROVED** [review]
:) I shoulda known you were out ahead of this problem. Pulling the latest, removing my hacky alias, and approving.

**Comment by wxactly** [comment]
Thanks! The downside is you have to manually edit your `/usr/local/etc/nginx/ts-dev.conf` file, and the `php.ini` file for each version of php you have installed... But at least you only have to do it once :)

**Pull request merged**
