### PR TITLE
Overhaul+update env setup script for 2016

### PR DESCRIPTION
**Pull request by wxactly**
Includes php56 (php-fpm), httpd24, and latest installation processes for
various dependencies

### CODE REVIEW

**Comment by Greg-Boggs** [comment]
Looks great. My only question is how do I get the changes to run on my laptop, I believe what I need to do is to uninstall php56 and uninstall apache22 and then run the script. Is that your understanding?

**Comment by wxactly** [comment]
Yes @Greg-Boggs - anyone who runs this script needs to be aware that they are "starting over" in some sense with apache and php. So you need to:

```
brew uninstall httpd22
brew uninstall php55 #or whatever version you're running right now
```

You'll lose any custom httpd config - including vhosts.

Also, one of the reasons this is waiting in a PR is because of the switch from mod-php -> php-fpm. (Any feedback here?) You'll have to update phpstorm xdebug settings to point to port 9001.

**Comment by Greg-Boggs** [comment]
The code looks good. So, I will test with my laptop after the mailchimp demo and let you know today.

**Comment by wxactly** [comment]
It worked for me. But proceed with caution - this branch may void your warranty ;)

**Comment by Greg-Boggs** [comment]
👍

**Comment by Greg-Boggs** [comment]
Full upgrade process:

```
cp ~/Sites/httpd-vhosts.conf .; brew uninstall --force php56; brew uninstall --force php55; brew uninstall --force php70; brew uninstall --force php56-opcache; brew uninstall --force httpd22
```

**Pull request merged**
